// flow-typed signature: 5e9d9a7bb9d8b6f7868f65e7ed709967
// flow-typed version: <<STUB>>/cssnano_v5.1.15/flow_v0.105.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'cssnano'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'cssnano' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'cssnano/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'cssnano/src/index' {
  declare module.exports: $Exports<'cssnano/src'>;
}
declare module 'cssnano/src/index.js' {
  declare module.exports: $Exports<'cssnano/src'>;
}
